"""Generate a small demonstration XML filter using synthetic OptimizedRules.

This is a smoke test to verify XML serialization produces valid output.
Not intended as end-to-end pipeline validation.
"""

from pathlib import Path
import sys

# Add parent directory to path for imports
sys.path.insert(0, str(Path(__file__).parent.parent))

from app.generator.xml_generator import generate, save
from app.generator.rule_models import OptimizedRule, OptimizationResult


def create_demo_rules():
    """Create synthetic OptimizedRules for demonstration."""

    # Exalted rule: Health + Armor T6+ on Body Armor
    exalted_rule = OptimizedRule(
        category="exalted",
        semantic_priority=1,
        score=0.9,
        build_count=150,
        occurrence_count=150,
        source_count=10,
        slot="Chest",
        item_types=[(3, 1)],  # Body Armor
        affixes=frozenset([
            (1, "Health", 6),      # +Health T6
            (49, "Armor", 6),      # +Armor T6
        ]),
    )

    # Exalted rule: Critical Strike Chance T7+ on Amulet
    exalted_rule_2 = OptimizedRule(
        category="exalted",
        semantic_priority=1,
        score=0.85,
        build_count=120,
        occurrence_count=120,
        source_count=8,
        slot="Amulet",
        item_types=[(8, None)],  # Amulet
        affixes=frozenset([
            (45, "Critical Strike Chance", 7),
        ]),
    )

    # Idol rule: Grand Idol with Minion Damage + Minion Health
    idol_rule = OptimizedRule(
        category="idol",
        semantic_priority=2,
        score=0.7,
        build_count=80,
        occurrence_count=80,
        source_count=5,
        slot="Idol",
        idol_sizes=["Grand Idol (2x4)"],
        modifiers=frozenset([
            (301, "Minion Damage", 1),
            (302, "Minion Health", 1),
        ]),
    )

    # Unique rule: Ravenous Void
    unique_rule = OptimizedRule(
        category="unique",
        semantic_priority=3,
        score=0.6,
        build_count=50,
        occurrence_count=50,
        source_count=3,
        slot="Ring",
        unique_items=frozenset([
            (101, "Ravenous Void"),
        ]),
    )

    # Unique rule: Ribbons of Blood
    unique_rule_2 = OptimizedRule(
        category="unique",
        semantic_priority=3,
        score=0.55,
        build_count=45,
        occurrence_count=45,
        source_count=3,
        slot="Belt",
        unique_items=frozenset([
            (102, "Ribbons of Blood"),
        ]),
    )

    return [exalted_rule, exalted_rule_2, idol_rule, unique_rule, unique_rule_2]


def main():
    """Generate demonstration XML filter."""
    output_dir = Path(__file__).parent.parent / "output"
    output_dir.mkdir(exist_ok=True)

    output_path = output_dir / "xml_generator_demo.xml"

    # Create optimization result with demo rules
    rules = create_demo_rules()
    result = OptimizationResult(
        rules=rules,
        final_count=len(rules),
        success=True,
    )

    # Generate XML with custom metadata
    metadata = {
        "name": "XML Generator Demo Filter",
        "description": "Demonstration filter generated by xml_generator.py",
    }

    # Save to file
    save(result, output_path, metadata=metadata)

    print(f"Demo XML generated: {output_path}")
    print(f"Rules: {len(rules)}")
    print(f"Categories: exalted, idol, unique")

    # Verify it parses
    import xml.etree.ElementTree as ET
    tree = ET.parse(output_path)
    root = tree.getroot()
    print(f"XML parse validation: OK (root tag: {root.tag})")

    # Print first few lines
    with open(output_path, "r", encoding="utf-8") as f:
        lines = f.readlines()[:15]
        print("\nFirst 15 lines of generated XML:")
        print("".join(lines))


if __name__ == "__main__":
    main()
